export enum SkipReason {
  DESABASTECIDO = 'DESABASTECIDO',
  SUJA = 'SUJA',
  AMASSADA = 'AMASSADA',
  DESEMBALADA = 'DESEMBALADA',
  DESCASCADA = 'DESCASCADA',
  TAG_ERRADO = 'TAG_ERRADO',
  NAO_LE_CODIGO = 'NAO_LE_CODIGO',
}
